library(tidyverse)
# Define the variables
variables <- data.frame(
  variable_description = c(
    "US state", 
    "numeric code for county", 
    "numeric code for community", 
    "community name", 
    "fold number", 
    "population for community",
    "mean people per household", 
    "percentage of population that is african american", 
    "percentage of population that is caucasian", 
    "percentage of population that is of asian heritage", 
    "percentage of population that is of hispanic heritage", 
    "percentage of population that is 12-21 in age", 
    "percentage of population that is 12-29 in age", 
    "percentage of population that is 16-24 in age", 
    "percentage of population that is 65 and over in age",
    "number of people living in areas classified as urban",
    "percentage of people living in areas classified as urban",
    "median household income", 
    "percentage of households with wage or salary income in 1989",
    "percentage of households with farm or self employment income in 1989", 
    "percentage of households with investment / rent income in 1989",
    "percentage of households with social security income in 1989",
    "percentage of households with public assistance income in 1989",
    "percentage of households with retirement income in 1989",
    "median family income",
    "per capita income",
    "per capita income for caucasians",
    "per capita income for african americans",
    "per capita income for native americans",
    "per capita income for people with asian heritage",
    "per capita income for people with other heritage",
    "per capita income for people with hispanic heritage",
    "number of people under the poverty level",
    "percentage of people under the poverty level",
    "percentage of people 25 and over with less than a 9th grade education",
    "percentage of people 25 and over that are not high school graduates",
    "percentage of people 25 and over with a bachelors degree or higher education",
    "percentage of people 16 and over, in the labor force, and unemployed",
    "percentage of people 16 and over who are employed",
    "percentage of people 16 and over who are employed in manufacturing",
    "percentage of people 16 and over who are employed in professional services",
    "percentage of people 16 and over who are employed in manufacturing",
    "percentage of people 16 and over who are employed in management or professional occupations",
    "percentage of males who are divorced",
    "percentage of males who have never married",
    "percentage of females who are divorced",
    "percentage of population who are divorced",
    "mean number of people per family",
    "percentage of families (with kids) that are headed by two parents",
    "percentage of kids in family housing with two parents",
    "percent of kids 4 and under in two parent households",
    "percent of kids age 12-17 in two parent households",
    "percentage of moms of kids 6 and under in labor force",
    "percentage of moms of kids under 18 in labor force",
    "number of kids born to never married",
    "percentage of kids born to never married",
    "total number of people known to be foreign born",
    "percentage of _immigrants_ who immigated within last 3 years",
    "percentage of _immigrants_ who immigated within last 5 years",
    "percentage of _immigrants_ who immigated within last 8 years",
    "percentage of _immigrants_ who immigated within last 10 years",
    "percent of _population_ who have immigrated within the last 3 years",
    "percent of _population_ who have immigrated within the last 5 years",
    "percent of _population_ who have immigrated within the last 8 years",
    "percent of _population_ who have immigrated within the last 10 years",
    "percent of people who speak only English",
    "percent of people who do not speak English well",
    "percent of family households that are large (6 or more)",
    "percent of all occupied households that are large (6 or more people)",
    "mean persons per household (numeric - decimal)",
    "mean persons per owner occupied household",
    "mean persons per rental household (numeric - decimal)",
    "percent of people in owner occupied households (numeric - decimal)",
    "percent of persons in dense housing (more than 1 person per room)",
    "percent of housing units with less than 3 bedrooms",
    "median number of bedrooms",
    "number of vacant households",
    "percent of housing occupied",
    "percent of households owner occupied",
    "percent of vacant housing that is boarded up",
    "percent of vacant housing that has been vacant more than 6 months",
    "median year housing units built",
    "percent of occupied housing units without phone (in 1990, this was rare!)",
    "percent of housing without complete plumbing facilities",
    "owner occupied housing - lower quartile value",
    "owner occupied housing - median value",
    "owner occupied housing - upper quartile value",
    "rental housing - lower quartile rent",
    "rental housing - median rent (Census variable H32B from file STF1A)",
    "rental housing - upper quartile rent",
    "median gross rent (Census variable H43A from file STF3A - includes utilities)",
    "median gross rent as a percentage of household income",
    "median owners cost as a percentage of household income - for owners with a mortgage",
    "median owners cost as a percentage of household income - for owners without a mortgage",
    "number of people in homeless shelters",
    "number of homeless people counted in the street",
    "percent of people foreign born",
    "percent of people born in the same state as currently living",
    "percent of people living in the same house as in 1985 (5 years before)",
    "percent of people living in the same city as in 1985 (5 years before)",
    "percent of people living in the same state as in 1985 (5 years before)",
    "number of sworn full time police officers",
    "sworn full time police officers per 100K population",
    "number of sworn full time police officers in field operations",
    "sworn full time police officers in field operations",
    "total requests for police",
    "total requests for police per 100K popuation",
    "total requests for police per police officer",
    "police officers per 100K population",
    "a measure of the racial match between the community and the police force",
    "percent of police that are caucasian",
    "percent of police that are african american",
    "percent of police that are hispanic",
    "percent of police that are asian",
    "percent of police that are minority of any kind",
    "number of officers assigned to special drug units",
    "number of different kinds of drugs seized",
    "police average overtime worked",
    "land area in square miles",
    "population density in persons per square mile",
    "percent of people using public transit for commuting",
    "number of police cars",
    "police operating budget",
    "percent of sworn full time police officers on patrol",
    "gang unit deployed",
    "percent of officers assigned to drug units",
    "police operating budget per population",
    "total number of violent crimes per 100K popuation"),
  Included = c(rep("Yes", ), rep("No", )),
  Type = c("Nominal", rep("Categorical", 2), "Text", "Categorical", 
           rep("Continuous", 119), "Categorical", rep("Continuous", 3))
)



# Load knitr package
library(kableExtra)
library(knitr)

# Create data frame
results <- data.frame(
  Package = c("", "glmnet", "glmnet", "", "xgboost (caret)", "xgboost (xgboost)", "", "spikeslab", "SSLASSO", "horseshoe", "bayesreg", "bayesreg", "BayesS5", "LaplacesDemon", "monomvn", "RJMCMC"),
  Method = c("Frequentist Methods", "LASSO", "Elastic Net", "Machine Learning Methods", "XGBoost", "XGBoost", "Bayesian Inference Methods", "Spike-and-slab prior", "Spike-and-slab LASSO prior", "Horseshoe prior", "Horseshoe prior", "Horseshoe+ prior", "SSS method", "Laplace approximation", "Bayesian LASSO", "rjmcmc"),
  TrueSignal = rep("", 16),
  FalsePositiveSignal = rep("", 16),
  FalseNegativeSignal = rep("", 16),
  stringsAsFactors = FALSE
)

# Render the table using kable
kable_output <- kable(results, align = "c", col.names = c("Package", "Method", "True Signal", "False Positive Signal", "False Negative Signal"), escape = FALSE) %>%
  kable_styling(full_width = FALSE, position = "center", bootstrap_options = c("striped"), font_size = 12) %>%
  pack_rows(index = c(1, 4, 7), label_row_css = "text-align: center;") %>%
  add_header_above(header = c(" " = 1, "Analysis Results" = 4), font_size = 15)

kable_output


